version: "3.9"

services:
  client:
    build: ./client
    ports:
      - "80:80"
    networks:
      - socialecho-net
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5000:5000"
    networks:
      - socialecho-net
    depends_on:
      - classifier

  

networks:
  socialecho-net:
    driver: overlay
