version: '3.8'

services:

  client:
    image: nitace/socialecho_client:latest
    ports:
      - "80:80"
    networks:
      - socialecho-net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker

  server:
    image: nitace/socialecho_server:latest
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env
    networks:
      - socialecho-net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker

  mongo:
    image: mongo:5
    volumes:
      - mongo-data:/data/db
    networks:
      - socialecho-net
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      replicas: 1

networks:
  socialecho-net:
    driver: overlay

volumes:
  mongo-data:
